[package]
name = "web_app"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
tokio = { version = "1.36.0", features = ["full"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
strip = true