[workspace]
members = [ "lambdas/event-handler", "lambdas/shared", "lambdas/publisher"]
resolver = "2"

[workspace.package]
version = "1.0.0"
authors = ["Benjamen Pyle", "James Eastham"]
license = "GPL-3"
edition = "2021"