version = 0.1
[default.deploy.parameters]
stack_name = "lambda-per-verb"
resolve_s3 = true
s3_prefix = "lambda-per-verb"
region = "eu-west-1"
profile = "sandbox"
capabilities = "CAPABILITY_IAM"
image_repositories = []
